---
title: "pfitmap-eval: Taxonomic distribution of NrdADJ subclasses"
author: "daniel.lundin@dbb.su.se"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  pdf_document:
    fig_caption: yes
    fig_height: 9
    fig_width: 8
    number_sections: yes
    toc: yes
  html_document:
    toc: yes
---

```{r libraries, echo=F}

suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(kfigr))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(readr))
suppressPackageStartupMessages(library(tidyr))

```

```{r constants, echo=F}

```

```{r functions, echo=F}

```

```{r db-connect, echo=F}

db = src_postgres('pfitmap-eval-prod')

```

```{r uniq-sp, echo=F}

# Creating a handle for NrdGRE proteins matching at least 0.9 of the profile,
# counting each species/protein combination just once.
uniq_sp_tbl = tbl(db, 'classified_proteins') %>%
  filter(psuperfamily == 'NrdGRE', prop_matching >= 0.9) %>%
  select(tdomain, tphylum, tclass, torder, tfamily, tgenus, tspecies, pclass, psubclass) %>%
  distinct()

```

# Overall subclass distribution

Counting proteins in the classified_proteins table matching at least 0.9 of the
profile length.

```{r overall-dist, echo=F}

overall_dist = collect(uniq_sp_tbl) %>%
  replace_na(list(tphylum='no phylum', psubclass='no subclass')) %>%
  group_by(tdomain, tphylum, pclass, psubclass) %>%
  summarise(n=n()) %>%
  ungroup()

major_phyla = overall_dist %>%
  filter(tphylum != '') %>%
  group_by(tdomain, tphylum, pclass, psubclass) %>%
  summarise(sum=sum(n)) %>%
  ungroup() %>%
  group_by(tdomain, tphylum, pclass) %>%
  summarise(max=max(sum)) %>%
  ungroup() %>%
  filter(max>=50) %>%
  transmute(tdomain, tphylum, major_phylum=tphylum, pclass)

overall_dist = overall_dist %>%
  left_join(major_phyla, by=c('tdomain', 'tphylum', 'pclass')) %>%
  replace_na(list(major_phylum='Other phyla'))

```

# NrdA

Based on presence in species, the distribution of NrdA subclasses is basically
one of distribution among bacterial phyla
(`r figr('overall-dist-nrda', T, type='Table')`).

```{r overall-dist-nrda, echo=F}

nrda_odist = overall_dist %>%
  filter(pclass=='NrdA') %>%
  group_by(tdomain, major_phylum, psubclass) %>%
  summarise(n=sum(n)) %>%
  ungroup() %>%
  spread(psubclass, n, fill=0) %>%
  arrange(tdomain, major_phylum)

kable(
  nrda_odist
)

```

```{r subclass-patterns-per-species, echo=F}

# Find the most abundant pattern of subclass presence in each species by
# enumerating subclasses in all strains
subclp_sp_w = collect(
    tbl(db, 'classified_proteins') %>% 
      filter(pclass=='NrdA', prop_matching>0.9) %>% 
      select(tdomain:tstrain, psubclass) %>% 
      distinct() %>%
      mutate(n=1)
  ) %>%
  replace_na(list(psubclass='NrdANS')) %>%
  union(
    collect(
      tbl(db, 'classified_proteins') %>% 
    	filter(pclass=='NrdD', prop_matching>0.9) %>% 
    	select(tdomain:tstrain, psubclass) %>% 
    	distinct() %>%
    	mutate(n=1)
    ) %>%
    replace_na(list(psubclass='NrdDNS'))
  ) %>%
  union(
    collect(
      tbl(db, 'classified_proteins') %>% 
    	filter(pclass=='NrdJ', prop_matching>0.9) %>% 
    	select(tdomain:tstrain, psubclass) %>% 
    	distinct() %>%
    	mutate(n=1)
    ) %>%
    replace_na(list(psubclass='NrdJNS'))
  ) %>%
  spread(psubclass, n, fill=0)

subclp_sp_w.colnames = names(subclp_sp_w)
subclp_sp_w.sbnames = subclp_sp_w.colnames[10:length(subclp_sp_w.colnames)]

# Calculate the most abundant subclass combination for each species (there will be ties <=> multiple rows)
subclp_sp_w = subclp_sp_w %>% 
  group_by_(.dots=lapply(setdiff(subclp_sp_w.colnames, c('tstrain')), as.symbol)) %>%
  summarise(n=n()) %>%
  ungroup() %>%
  group_by_(.dots=lapply(subclp_sp_w.colnames[1:8], as.symbol)) %>%
  top_n(1, n) %>%
  ungroup()

# Write wide table to file for reference
write_tsv(subclp_sp_w, 'tables/NrdADJ_subclass_patterns.tsv')

subclp_sp_l = subclp_sp_w %>%
  select(-n) %>% 
  gather_('subclass','n', subclp_sp_w.colnames[10:length(subclp_sp_w.colnames)]) %>% 
  filter(n>0)

```

## What other RNRs do NrdE, NrdAi and NrdAz-bearing organisms have?

```{r nrde-repertoire-patterns, echo=F}

# Subset the subclass pattern table to contain only NrdE, NrdAi and NrdAz
# species, make sure it contains patterns occuring at least 10 times, grouped
# by organism class and patterns.
d = subclp_sp_w %>%
  filter(NrdE >= 1 | NrdAi >= 1 | NrdAz >= 1) %>%
  group_by_(.dots=lapply(c(c('tdomain', 'tphylum','tclass'), subclp_sp_w.sbnames), as.symbol)) %>% 
  summarise(np=n()) %>% 
  ungroup() %>% 
  filter(np>=10) %>% 
  gather_('psubclass', 'n', subclp_sp_w.sbnames) %>% # This line, and the following two, deletes subclasses not found in any pattern that's of interest
  filter(n>0) %>% 
  distinct() %>%
  mutate(n=psubclass) %>%
  spread(psubclass, n, fill='')

c = names(d)

d = d %>%
  unite_('pattern', c[5:length(c)], sep=':') %>%
  mutate(pattern=gsub('::*', ':', pattern)) %>%
  mutate(pattern=sub('^:', '', pattern)) %>%
  mutate(pattern=sub(':$', '', pattern)) %>%
  select(tdomain, tphylum, tclass, pattern, np) %>%
  arrange(tdomain, tphylum, tclass, desc(np))

kable(
  d,
  col.names=c('Domain', 'Phylum', 'Class', 'Subclass pattern', 'Count')
)

write_tsv(d, 'tables/nrde.subclass_patterns.tsv')

```

```{r class-patterns, echo=F}

# Calculate the patterns of classes in all strains, count each species as one occurrence.
sp_class_patterns = collect(
    tbl(db, 'classified_proteins') %>%
      filter(psuperfamily == 'NrdGRE', prop_matching >= 0.9) %>%
      select(tdomain, tphylum, tclass, torder, tfamily, tgenus, tspecies, tstrain, pclass, psubclass) %>%
      distinct() %>%
      filter(tgenus!='') 
  ) %>%
  left_join(major_phyla, by=c('tdomain','tphylum','pclass')) %>%
  replace_na(list(major_phylum='Other phyla')) %>%
  group_by(tdomain, tphylum, tclass, torder, tfamily, tgenus, tspecies, tstrain, major_phylum, pclass) %>%
  summarise(n=n()) %>%
  ungroup() %>%
  spread(pclass, n, fill=0) %>%
  unite(class_pattern, NrdA:NrdJ, sep=':') %>%
  select(-tstrain) %>%
  distinct()

### dom_fam_class_patterns = sp_class_patterns %>%
###   group_by(tdomain, tphylum, tclass, torder, tfamily, major_phylum, class_pattern) %>%
###   summarise(n=n())
### 
### maxfam = dom_fam_class_patterns %>%
###   top_n(1, n) %>%
###   ungroup() %>%
###   mutate(max=n) %>%
###   select(-class_pattern, -n, -major_phylum) %>%
###   distinct()
### 
### dom_fam_class_patterns = dom_fam_class_patterns %>%
###   ungroup() %>%
###   inner_join(maxfam, by=c('tdomain','tphylum','tclass','torder','tfamily')) %>%
###   filter(n/max>0.1)

```
