---
title: "Pfitmap-eval: Distribution of scores per sequence and profile"
author: "daniel.lundin@dbb.su.se"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  pdf_document:
    fig_caption: yes
    fig_height: 9
    fig_width: 8
    number_sections: yes
    toc: yes
  html_document:
    toc: yes
---

```{r libraries, echo=F}

suppressPackageStartupMessages(library(dplyr));
suppressPackageStartupMessages(library(ggplot2));
suppressPackageStartupMessages(library(kfigr));
suppressPackageStartupMessages(library(knitr));
#suppressPackageStartupMessages(library(readr));
suppressPackageStartupMessages(library(tidyr));

```

```{r constants, echo=F}

```

```{r functions, echo=F}

```

```{r db-connect, echo=F}

db = src_postgres('pfitmap-eval-prod')

```

```{r fscores, echo=F}

fscores = tbl(db, sql("
SELECT 
  fname,
  gi,
  accno,
  name,
  sequence,
  score_pattern,
  fscore, fbest_score,
  cscore, cbest_score,
  scscore, scbest_score
FROM
  fscores
WHERE 
  db = 'gb'
"
    )
  ) %>%
  transmute(
    fname, gi, accno, name, sequence,
    pattern=score_pattern, 
    family=fscore, fbest_score,
    class=cscore, cbest_score,
    subclass=scscore, scbest_score
  )

fscoresl = gather(collect(fscores), key=rank, value=score, family, class, subclass)

### fscores_summary = tbl(db, sql('select fname, score_pattern, count(*), avg(fscore), avg(cscore), avg(scscore) from fscores group by 1, 2 order by 1,2'))

```

```{r cscores, echo=F}

cscores = tbl(db, sql("
SELECT 
  cname,
  gi,
  accno,
  name,
  sequence,
  score_pattern,
  cscore, cbest_score,
  scscore, scbest_score,
  gscore, gbest_score
FROM
  cscores
WHERE 
  db = 'gb'
"
    )
  ) %>%
  transmute(
    cname, gi, accno, name, sequence,
    pattern=score_pattern, 
    class=cscore, cbest_score,
    subclass=scscore, scbest_score,
    group=gscore, gbest_score
  )

cscoresl = gather(collect(cscores), key=rank, value=score, class, subclass, group)

### cscores_summary = tbl(db, sql('select fname, score_pattern, count(*), avg(fscore), avg(cscore), avg(scscore) from cscores group by 1, 2 order by 1,2'))

```

```{r fscores-hist, echo=F}

ggplot(fscoresl, aes(x=score, fill=pattern)) + 
  geom_histogram(position='dodge', binwidth=30) + 
  facet_wrap(~rank, ncol=1) + 
  ylim(c(0,1000))

```


```{r fscores-sum, echo=F}

### kable(
###   fscores %>% 
###     filter(!is.na(family_score)) %>%
###     group_by(family) %>% 
###     summarize(
###       n=n(), 
###       min_family=min(family),
###       mean_family=mean(family),
###       max_family=max(family),
###       min_class=min(class),
###       mean_class=mean(class),
###       max_class=max(class),
###       min_subclass=min(subclass),
###       mean_subclass=mean(subclass),
###       max_subclass=max(subclass)
###     ) %>%
###     arrange(family),
###   col.names = c('Family', 'N.', 'Min', 'Fmean', 'Max', 'Min', 'Classmean', 'Max', 'Min', 'SBmean', 'Max')
### )

```

```{r class-to-family-scorediff, echo=F}

c2fdiff = collect(fscores) %>%
    transmute(
      name=sprintf("Family: %s", fname), 
      c2diff=class-family, 
      c2diffrel=(class-family)/family,
      best_score=cbest_score
    ) %>%
    union(
      collect(cscores) %>% 
        filter(!is.na(subclass)) %>%
        transmute(
	  name=sprintf("Class: %s", cname), 
	  c2diff=subclass-class, 
	  c2diffrel=(subclass-class)/class,
	  best_score=scbest_score
	)
    )

```

```{r reldiff-plot, echo=F}

ggplot(c2fdiff, aes(x=c2diffrel, fill=best_score)) +
  geom_histogram(position = 'dodge') +
  geom_vline(xintercept=0, colour='red') +
  facet_wrap(~name, scales='free')

```
